#!/bin/bash -l
#SBATCH --job-name="script"
#SBATCH --account="uzg2"
#SBATCH --time=00:02:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu
#SBATCH --hint=nomultithread

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

for N in 2 4 8 16; do
      srun ./dot.openacc $N $nstep
done
